apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: dga-ai
data:
  litellm-config.yaml: |
    # LiteLLM Proxy Configuration with Redis Caching
    model_list:
      - model_name: Qwen3-32B-AWQ
        litellm_params:
          model: openai/Qwen3-32B-AWQ
          api_base: "http://qwen3-32b-awq:8000/v1"
          api_key: "dummy"
          api_type: "openai"
          tool_call_parser: hermes
        model_info:
          context_window: 10240

      - model_name: Qwen2.5-14B-Instruct
        litellm_params:
          model: openai/Qwen2.5-14B-Instruct
          api_base: "http://qwen2-5-14b-instruct-lb:8000/v1"
          api_key: "dummy"
          api_type: "openai"
          tool_call_parser: hermes
        model_info:
          context_window: 6144

      - model_name: Llama-3.1-8B-Instruct
        litellm_params:
          model: openai/Llama-3.1-8B-Instruct
          api_base: "http://llama-3-1-8b-instruct:8000/v1"
          api_key: "dummy"
          api_type: "openai"
          tool_call_parser: llama3_json
        model_info:
          context_window: 6144

      - model_name: Qwen3-30B-A3B
        litellm_params:
          model: openai/Qwen3-30B-A3B
          api_base: "http://qwen3-30b-a3b:8000/v1"
          api_key: "dummy"
          api_type: "openai"
          tool_call_parser: hermes
        model_info:
          context_window: 6144

   

    general_settings:
      database_url: null
      public_routes:
        - "/health"
        - "/health/liveliness"
        - "/health/readiness"

    litellm_settings:
      set_verbose: true
      drop_params: true
      cache: true
      enable_auto_tool_choice: true
      cache_params:
        type: "redis"
        host: "redis-master"
        port: 6379
        password: "your_redis_password"
        ttl: 300
        namespace: "litellm_cache"
